# Lab 5 Evaluation

## Cell 1: Import all libraries

In [ ]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder

## Cell 2: Load dataset

In [18]:
df = pd.read_excel("dataset_lab5.xlsx")
df

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2   NaN  35000.0    Male       Dhaka
3  30.0      NaN  Female      Sylhet
4  28.0  40000.0     NaN       Dhaka
5  35.0  45000.0    Male         NaN

## Cell 3: Identify missing values

In [19]:
df.isnull().sum()

Age       1
Income    1
Gender    1
City      1
dtype: int64

## Cell 4: Replace missing Age value with mean

In [20]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2  27.6  35000.0    Male       Dhaka
3  30.0      NaN  Female      Sylhet
4  28.0  40000.0     NaN       Dhaka
5  35.0  45000.0    Male         NaN

## Cell 5: Replace missing Income value with mean

In [21]:
df["Income"] = df["Income"].fillna(df["Income"].mean())
df

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2  27.6  35000.0    Male       Dhaka
3  30.0  35000.0  Female      Sylhet
4  28.0  40000.0     NaN       Dhaka
5  35.0  45000.0    Male         NaN

## Cell 6: Replace missing Gender value with mode

In [22]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2  27.6  35000.0    Male       Dhaka
3  30.0  35000.0  Female      Sylhet
4  28.0  40000.0    Male       Dhaka
5  35.0  45000.0    Male         NaN

## Cell 7: Replace missing City value with mode

In [23]:
df["City"] = df["City"].fillna(df["City"].mode()[0])
df

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2  27.6  35000.0    Male       Dhaka
3  30.0  35000.0  Female      Sylhet
4  28.0  40000.0    Male       Dhaka
5  35.0  45000.0    Male       Dhaka

## Cell 8: Confirm no missing values

In [24]:
df.isnull().sum()

Age       0
Income    0
Gender    0
City      0
dtype: int64

## Cell 9: Apply Min-Max Scaling to Age and Income

In [25]:
Minmax = MinMaxScaler()

df[["Age", "Income"]] = Minmax.fit_transform(df[["Age", "Income"]])

df

        Age  Income  Gender        City
0  0.000000    0.00    Male       Dhaka
1  0.333333    0.25  Female  Chittagong
2  0.506667    0.50    Male       Dhaka
3  0.666667    0.50  Female      Sylhet
4  0.533333    0.75    Male       Dhaka
5  1.000000    1.00    Male       Dhaka

## Cell 10: Apply Label Encoding to Gender

In [26]:
le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])

df

        Age  Income  Gender        City
0  0.000000    0.00       1       Dhaka
1  0.333333    0.25       0  Chittagong
2  0.506667    0.50       1       Dhaka
3  0.666667    0.50       0      Sylhet
4  0.533333    0.75       1       Dhaka
5  1.000000    1.00       1       Dhaka

## Cell 11: Apply One Hot Encoding to City

In [27]:
ohe = OneHotEncoder(sparse_output=False, dtype=np.int32)

encoded = ohe.fit_transform(df[["City"]])

city_encoded = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(["City"])
)

city_encoded

   City_Chittagong  City_Dhaka  City_Sylhet
0                0           1            0
1                1           0            0
2                0           1            0
3                0           0            1
4                0           1            0
5                0           1            0

## Cell 12: Combine One Hot Encoded City with dataset

In [28]:
df = pd.concat([df.drop("City", axis=1), city_encoded], axis=1)

df

        Age  Income  Gender  City_Chittagong  City_Dhaka  City_Sylhet
0  0.000000    0.00       1                0           1            0
1  0.333333    0.25       0                1           0            0
2  0.506667    0.50       1                0           1            0
3  0.666667    0.50       0                0           0            1
4  0.533333    0.75       1                0           1            0
5  1.000000    1.00       1                0           1            0