# Lab 4 – Data Preprocessing

## Cell 1: Import all libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder

## Cell 2: Load dataset and display dataset before preprocessing

In [2]:
df = pd.read_excel("dataset_lab5.xlsx")
df

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2   NaN  35000.0    Male       Dhaka
3  30.0      NaN  Female      Sylhet
4  28.0  40000.0     NaN       Dhaka
5  35.0  45000.0    Male         NaN

## Cell 3: Identify missing values

In [3]:
df.isnull().sum()

Age       1
Income    1
Gender    1
City      1
dtype: int64

## Cell 4: Create a copy of the dataset for preprocessing

In [4]:
df_full = df.copy()
df_full

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2   NaN  35000.0    Male       Dhaka
3  30.0      NaN  Female      Sylhet
4  28.0  40000.0     NaN       Dhaka
5  35.0  45000.0    Male         NaN

## Cell 5: Replace missing Age value with mean

In [5]:
df_full["Age"] = df_full["Age"].fillna(df_full["Age"].mean())
df_full["Age"].isnull().sum()

np.int64(0)

## Cell 6: Replace missing Income value with mean

In [6]:
df_full["Income"] = df_full["Income"].fillna(df_full["Income"].mean())
df_full["Income"].isnull().sum()

np.int64(0)

## Cell 7: Replace missing Gender value with mode

In [7]:
df_full["Gender"] = df_full["Gender"].fillna(df_full["Gender"].mode()[0])
df_full["Gender"].isnull().sum()

np.int64(0)

## Cell 8: Replace missing City value with mode

In [8]:
df_full["City"] = df_full["City"].fillna(df_full["City"].mode()[0])
df_full["City"].isnull().sum()

np.int64(0)

## Cell 9: Confirm no missing values

In [9]:
df_full.isnull().sum()

Age       0
Income    0
Gender    0
City      0
dtype: int64

## Cell 10: Separate numeric and categorical columns

In [10]:
num_cols = df_full.select_dtypes(include=np.number).columns
cat_cols = df_full.select_dtypes(include=["object", "category", "string"]).columns
num_cols, cat_cols

(Index(['Age', 'Income'], dtype='object'),
 Index(['Gender', 'City'], dtype='object'))

## Cell 11: Standard Scaling

In [11]:
scaler = StandardScaler()
scaled = scaler.fit_transform(df_full[num_cols])
scaled_df = pd.DataFrame(scaled, columns=num_cols)
scaled_df.head()

            Age    Income
0 -1.663746e+00 -1.549193
1 -5.691763e-01 -0.774597
2  7.777386e-16  0.000000
3  5.253935e-01  0.000000
4  8.756558e-02  0.774597

## Cell 12: Min-Max Scaling

In [12]:
Minmax = MinMaxScaler()
norm = Minmax.fit_transform(df_full[num_cols])
norm_df = pd.DataFrame(norm, columns=num_cols)
norm_df.head()

        Age  Income
0  0.000000    0.00
1  0.333333    0.25
2  0.506667    0.50
3  0.666667    0.50
4  0.533333    0.75

## Cell 13: Apply Label Encoding to Gender

In [13]:
le = LabelEncoder()
df_full["Gender"] = le.fit_transform(df_full["Gender"])
df_full

    Age   Income  Gender        City
0  20.0  25000.0       1       Dhaka
1  25.0  30000.0       0  Chittagong
2  27.6  35000.0       1       Dhaka
3  30.0  35000.0       0      Sylhet
4  28.0  40000.0       1       Dhaka
5  35.0  45000.0       1       Dhaka

## Cell 14: Apply One-Hot Encoding to City

In [14]:
ohe = OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore", dtype=np.int32)
encoded = ohe.fit_transform(df_full[["City"]])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(["City"]))

display(df_full[["City"]].head())
display(encoded_df.head())

         City
0       Dhaka
1  Chittagong
2       Dhaka
3      Sylhet
4       Dhaka

   City_Dhaka  City_Sylhet
0           1            0
1           0            0
2           1            0
3           0            1
4           1            0

## Cell 15: Final dataset using Min-Max Scaling

In [15]:
df_minmax = pd.concat([norm_df, df_full[["Gender"]], encoded_df], axis=1)
df_minmax

        Age  Income  Gender  City_Dhaka  City_Sylhet
0  0.000000    0.00       1           1            0
1  0.333333    0.25       0           0            0
2  0.506667    0.50       1           1            0
3  0.666667    0.50       0           0            1
4  0.533333    0.75       1           1            0
5  1.000000    1.00       1           1            0

## Cell 16: Final dataset using Standard Scaling

In [16]:
df_standard = pd.concat([scaled_df, df_full[["Gender"]], encoded_df], axis=1)
df_standard

            Age    Income  Gender  City_Dhaka  City_Sylhet
0 -1.663746e+00 -1.549193       1           1            0
1 -5.691763e-01 -0.774597       0           0            0
2  7.777386e-16  0.000000       1           1            0
3  5.253935e-01  0.000000       0           0            1
4  8.756558e-02  0.774597       1           1            0
5  1.619963e+00  1.549193       1           1            0

## Cell 17: Display dataset before and after preprocessing

In [17]:
print("Original DataFrame: ")
display(df)

print("\nAfter Preprocessing with Min-Max Scaling: ")
display(df_minmax)

print("\nAfter Preprocessing with Standard Scaling: ")
display(df_standard)

Original DataFrame:

    Age   Income  Gender        City
0  20.0  25000.0    Male       Dhaka
1  25.0  30000.0  Female  Chittagong
2   NaN  35000.0    Male       Dhaka
3  30.0      NaN  Female      Sylhet
4  28.0  40000.0     NaN       Dhaka
5  35.0  45000.0    Male         NaN

After Preprocessing with Min-Max Scaling:

        Age  Income  Gender  City_Dhaka  City_Sylhet
0  0.000000    0.00       1           1            0
1  0.333333    0.25       0           0            0
2  0.506667    0.50       1           1            0
3  0.666667    0.50       0           0            1
4  0.533333    0.75       1           1            0
5  1.000000    1.00       1           1            0

After Preprocessing with Standard Scaling:

            Age    Income  Gender  City_Dhaka  City_Sylhet
0 -1.663746e+00 -1.549193       1           1            0
1 -5.691763e-01 -0.774597       0           0            0
2  7.777386e-16  0.000000       1           1            0
3  5.253935e-01  0.000000       0           0            1
4  8.756558e-02  0.774597       1           1            0
5  1.619963e+00  1.549193       1           1            0